sudo: required
language: c
services:
    - docker

before_install:
- docker pull zhuangjw/docker_gc

script:
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make MET=geosfp GRID=4x5"
